import type { Metadata } from "next";
import { AppLayout } from "@/_shared/components/AppLayout";
import "@/styles/index.css";

export const metadata: Metadata = {
  title: "Expenses App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
